version: '3.8'

# To start:
# - docker-compose up
# To finish:
# - docker-compose down

services:
  db:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_DB: station
      POSTGRES_USER: station_user
      POSTGRES_PASSWORD: 1234
    ports:
      - 5434:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/postgresql/data